# Generated by Django 4.2.13 on 2024-06-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('dept_code', models.IntegerField()),
                ('dept_name', models.CharField(max_length=255)),
                ('dept_abrv', models.CharField(max_length=255)),
                ('mana_tp', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_biz', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('addr1', models.CharField(blank=True, max_length=255, null=True)),
                ('addr2', models.CharField(blank=True, max_length=255, null=True)),
                ('priox', models.CharField(blank=True, max_length=255, null=True)),
                ('dept_stat', models.CharField(blank=True, max_length=255, null=True)),
                ('up_dept_code', models.CharField(blank=True, max_length=255, null=True)),
                ('sum_dept_code', models.CharField(blank=True, max_length=255, null=True)),
                ('cur_dept_code', models.CharField(blank=True, max_length=255, null=True)),
                ('buseo_tp', models.CharField(blank=True, max_length=255, null=True)),
                ('dso_code', models.CharField(blank=True, max_length=255, null=True)),
                ('org_cd', models.CharField(blank=True, max_length=255, null=True)),
                ('insert_date', models.CharField(max_length=255)),
                ('insert_user', models.CharField(blank=True, max_length=255, null=True)),
                ('update_date', models.CharField(max_length=255)),
                ('update_user', models.CharField(blank=True, max_length=255, null=True)),
                ('acct_tp', models.CharField(blank=True, max_length=255, null=True)),
                ('st_tp', models.CharField(blank=True, max_length=255, null=True)),
                ('st_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('begda', models.CharField(max_length=255)),
                ('endda', models.CharField(max_length=255)),
            ],
        ),
    ]
