# Generated by Django 4.2.13 on 2024-06-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
