# Generated by Django 4.2.13 on 2024-06-09 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0005_employee_addr1_employee_addr2_employee_annc_dt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='inert_date',
            new_name='insert_date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='inser_user',
            new_name='insert_user',
        ),
    ]
