# Generated by Django 4.2.13 on 2024-06-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0006_rename_inert_date_employee_insert_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
