# Generated by Django 4.2.13 on 2024-06-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0007_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254)),
                ('ldap_host', models.CharField(max_length=100)),
            ],
        ),
    ]
