# Generated by Django 4.2.13 on 2024-06-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0008_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='ldap_host',
        ),
        migrations.AddField(
            model_name='setting',
            name='ad_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='ad_server',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='ad_user',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='base_dn',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
