# Generated by Django 4.2.13 on 2024-06-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0009_remove_setting_ldap_host_setting_ad_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='expire_day',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
