# Generated by Django 4.2.13 on 2024-06-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0010_setting_expire_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='expire_day',
            new_name='license',
        ),
    ]
