# Generated by Django 4.2.13 on 2024-06-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0011_rename_expire_day_setting_license'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='license',
            new_name='license_key',
        ),
    ]
