# Generated by Django 4.2.13 on 2024-06-24 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0015_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='group_csv_path',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='user_csv_path',
        ),
    ]
