# Generated by Django 4.2.13 on 2024-06-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0016_remove_setting_group_csv_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_path', models.CharField(max_length=255)),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
            ],
        ),
    ]
