# Generated by Django 4.2.13 on 2024-06-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0017_group_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group_Schedule',
        ),
    ]
