# Generated by Django 4.2.13 on 2024-06-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0018_delete_group_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='group_csv_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
