# Generated by Django 4.2.13 on 2024-06-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0019_schedule_group_csv_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day_of_week',
        ),
    ]
