# Generated by Django 4.2.13 on 2024-06-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0020_remove_schedule_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
