# Generated by Django 4.2.13 on 2024-07-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0022_rename_addr1_employee_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='begda',
            new_name='ou_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='addr1',
        ),
        migrations.RemoveField(
            model_name='department',
            name='addr2',
        ),
        migrations.RemoveField(
            model_name='department',
            name='buseo_tp',
        ),
        migrations.RemoveField(
            model_name='department',
            name='cur_dept_code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='dept_abrv',
        ),
        migrations.RemoveField(
            model_name='department',
            name='dept_code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='dept_stat',
        ),
        migrations.RemoveField(
            model_name='department',
            name='dso_code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='endda',
        ),
        migrations.RemoveField(
            model_name='department',
            name='insert_date',
        ),
        migrations.RemoveField(
            model_name='department',
            name='insert_user',
        ),
        migrations.RemoveField(
            model_name='department',
            name='mana_tp',
        ),
        migrations.RemoveField(
            model_name='department',
            name='org_cd',
        ),
        migrations.RemoveField(
            model_name='department',
            name='priox',
        ),
        migrations.RemoveField(
            model_name='department',
            name='st_nm',
        ),
        migrations.RemoveField(
            model_name='department',
            name='st_tp',
        ),
        migrations.RemoveField(
            model_name='department',
            name='sum_dept_code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tax_biz',
        ),
        migrations.RemoveField(
            model_name='department',
            name='up_dept_code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='department',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='department',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create Date'),
        ),
    ]
