# Generated by Django 4.2.13 on 2024-07-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0023_rename_begda_department_ou_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='ftp_host',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='ftp_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='ftp_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='ftp_remote_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='ftp_username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
