# Generated by Django 4.2.13 on 2024-07-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0024_setting_ftp_host_setting_ftp_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='ftp_path',
        ),
    ]
