# Generated by Django 4.2.13 on 2024-07-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0025_remove_setting_ftp_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='ftp_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
