# Generated by Django 4.2.13 on 2024-07-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insa', '0026_setting_ftp_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='root_dn',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
